# Generated by Django 5.0.2 on 2024-03-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('standard', 'Standard User')], default='standard', max_length=10),
        ),
    ]
