# Generated by Django 5.0.2 on 2024-03-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
