# Generated by Django 5.0.2 on 2024-03-09 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_school', '0002_alter_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='report',
        ),
        migrations.AddField(
            model_name='student',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_school.report'),
        ),
    ]
