# Generated by Django 5.0.2 on 2024-03-06 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_school', '0002_rename_position_nonstudent_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonstudent',
            old_name='emergency_contact_phone',
            new_name='next_kin_phone',
        ),
        migrations.RenameField(
            model_name='nonstudent',
            old_name='emergency_contact_name',
            new_name='next_of_kin',
        ),
    ]
