# Generated by Django 5.0.2 on 2024-03-06 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_school', '0003_rename_emergency_contact_phone_nonstudent_next_kin_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonstudent',
            old_name='next_kin_phone',
            new_name='next_of_kin_phone',
        ),
    ]
