# Generated by Django 5.0.2 on 2024-03-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_school', '0003_remove_customuser_is_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonstudent',
            name='date_of_joining',
            field=models.DateField(null=True),
        ),
    ]
