# Generated by Django 5.0.2 on 2024-03-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_school', '0005_application_city_alter_application_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='city_or_District',
            new_name='city_or_district',
        ),
        migrations.AlterField(
            model_name='application',
            name='document_name',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('received', 'Received'), ('review', 'Under Review'), ('admitted', 'Admitted')], default='received', max_length=10, null=True),
        ),
    ]
