# Generated by Django 5.0.2 on 2024-03-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_school', '0007_alter_application_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('review', 'Under Review'), ('admitted', 'Admitted'), ('completed', 'Completed')], default='review', max_length=10, null=True),
        ),
    ]
