# Generated by Django 5.0.2 on 2024-03-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_school', '0008_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('review', 'Under Review'), ('admitted', 'Admitted'), ('completed', 'Completed')], max_length=10, null=True),
        ),
    ]
