# Generated by Django 5.0.2 on 2024-03-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_school', '0009_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ManyToManyField(to='my_school.subject'),
        ),
    ]
