# Generated by Django 5.0.2 on 2024-03-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_school', '0011_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
